"""
energy_agent.py
==========================================
AI Home Energy Optimizer Agent

Uses:
- LangChain v1.x
- ChatGroq
- create_agent()

Requirements
------------

pip install \
langchain \
langchain-groq \
langchain-core \
python-dotenv \
rich

Environment
-----------

GROQ_API_KEY=<your api key>

Project Structure
-----------------

energy-agent/

│
├── home_energy_dataset.csv
├── tools1.py
├── tools2.py
├── tools3.py
├── energy_agent.py
└── .env
"""

from dotenv import load_dotenv
import os

from rich.console import Console
from rich.markdown import Markdown

from langchain.agents import create_agent
from langchain_groq import ChatGroq

from tools1 import (
    load_dataset,
    TOOLS as TOOLS1
)

from tools2 import (
    TOOLS as TOOLS2
)

from tools3 import (
    TOOLS as TOOLS3
)

###############################################################################
# Load Environment
###############################################################################

load_dotenv()

console = Console()

###############################################################################
# Load Dataset
###############################################################################

DATASET = "home_energy_dataset.csv"

console.print(
    "[bold cyan]Loading Dataset...[/bold cyan]"
)

result = load_dataset.invoke(
    {
        "csv_path": DATASET
    }
)

console.print(result)

###############################################################################
# Create LLM
###############################################################################

llm = ChatGroq(

    model="llama-3.3-70b-versatile",

    temperature=0,

    api_key=""

)

###############################################################################
# Register Tools
###############################################################################

TOOLS = []

TOOLS.extend(TOOLS1)
TOOLS.extend(TOOLS2)
TOOLS.extend(TOOLS3)

###############################################################################
# Create Agent
###############################################################################

SYSTEM_PROMPT = """
You are an expert Home Energy Optimization Consultant.

You have access to many analytical tools.

Always use tools whenever numerical analysis
or statistics are required.

Never guess values.

When users ask for recommendations,

first gather relevant information using tools.

Then produce practical recommendations.

Be concise.

Where appropriate provide:

• Energy Summary

• Appliance Analysis

• Cost Analysis

• Peak Usage

• Optimization Suggestions

• Estimated Savings

Always explain WHY you recommend something.
"""

agent = create_agent(

    model=llm,

    tools=TOOLS,

    system_prompt=SYSTEM_PROMPT,

)

###############################################################################
# Interactive Chat
###############################################################################

console.print()

console.print(
    "[bold green]"
    "AI Home Energy Optimizer"
    "[/bold green]"
)

console.print(
    "Type 'exit' to quit.\n"
)

while True:

    question = console.input(

        "[bold yellow]You[/bold yellow] : "

    )

    if question.lower() in (

        "exit",

        "quit",

        "bye"

    ):

        break

    response = agent.invoke(

        {

            "messages": [

                {

                    "role": "user",

                    "content": question

                }

            ]

        }

    )

    answer = response["messages"][-1].content

    console.print()

    console.print(

        Markdown(answer)

    )

    console.print()

###############################################################################
# Example Questions
###############################################################################

"""
How much electricity did I consume this month?

What is my total electricity bill?

Which appliance consumes the most power?

Show me the top 5 energy consuming appliances.

What percentage of electricity is consumed by HVAC?

Which day consumed the highest electricity?

Which day consumed the least electricity?

What are my peak usage hours?

Compare weekday vs weekend usage.

How much electricity was generated by solar?

How much grid power am I using?

How much energy did my EV charging consume?

How much energy did my water heater consume?

Find anomalies in my electricity usage.

Is HVAC strongly related to temperature?

Prepare an energy optimization report.

Give me recommendations to reduce my bill.

Estimate my monthly savings.

Create an optimization strategy.

Suggest changes to reduce my electricity bill by 20%.

Generate a complete energy audit.
"""